-- RAM writer for encode

--if not emu then
--  error("This script runs under DeSmuME.")
--end

local file = io.open("framedata.lua.inl", "w")
if file == nil then
  error("File could not be opened.")
end
file:write("frame={\n")

emu.registerafter(function()
	file:write("\t{")
	file:write(string.format("count=%d,", emu.framecount()))
	file:write(string.format("lagcount=%d,", emu.lagcount()))
	file:write(string.format("lagged=%s,", (emu.lagged() and "true" or "false")))
	file:write(string.format("x=%u,", memory.readdword(0x020ca95c)))
	file:write(string.format("y=%u,", memory.readdword(0x020ca960)))
	file:write(string.format("xv=%d,", memory.readdwordsigned(0x020ca968)))
	file:write(string.format("yv=%d,", memory.readdwordsigned(0x020ca96c)))
	file:write(string.format("random=%u,", memory.readdword(0x020c07e4)))
	file:write(string.format("ingamecount=%d,", memory.readdword(0x020f703c)))
	file:write(string.format("inv1=%d,", memory.readbyte(0x020ca9f3))) -- invincibility
	file:write(string.format("inv2=%d,", memory.readbyte(0x020caa24)))
	--file:write(string.format("hp=%d,", memory.readword(0x020f7410)))
	--file:write(string.format("maxhp=%d,", memory.readword(0x020f7412)))
	--file:write(string.format("mp=%d,", memory.readword(0x020f7414)))
	--file:write(string.format("maxmp=%d,", memory.readword(0x020f7416)))
	--file:write(string.format("exp=%d,", memory.readdword(0x020f7448)))
	file:write(string.format("seal=%d,", memory.readbyte(0x020f2a88)))
	file:write(string.format("sealsub=%d,", memory.readbyte(0x020f2a8c)))
	--file:write(string.format("succubustimer=%d,", memory.readdword(0x020ced88)))
	file:write(string.format("menaceflags=%u,", memory.readbyte(0x020f718a)))
	file:write(string.format("xsuspend=%u,", memory.readdword(0x020fed88)))
	file:write(string.format("ysuspend=%u,", memory.readdword(0x020fed8c)))
	file:write(string.format("farmorhp=%d,", memory.readword(0x020d36a8)))
	file:write(string.format("farmorinv1=%d,", memory.readbyte(0x020d3513)))
	file:write(string.format("farmorinv2=%d,", memory.readbyte(0x020d3514)))
	file:write(string.format("farmorinv3=%d,", memory.readbyte(0x020d3515)))
	file:write(string.format("balorehp=%d,", memory.readword(0x020d26e8)))
	file:write(string.format("baloreinv1=%d,", memory.readbyte(0x020d2553)))
	file:write(string.format("baloreinv2=%d,", memory.readbyte(0x020d2554)))
	file:write(string.format("baloreinv3=%d,", memory.readbyte(0x020d2555)))
	file:write(string.format("dmitriihp=%d,", memory.readword(0x020d2ec8)))
	file:write(string.format("dmitriiinv1=%d,", memory.readbyte(0x020d2d33)))
	file:write(string.format("dmitriiinv2=%d,", memory.readbyte(0x020d2d34)))
	file:write(string.format("dmitriiinv3=%d,", memory.readbyte(0x020d2d35)))
	file:write(string.format("mapx=%d,", memory.readbyte(0x0210F018)))
	file:write(string.format("mapy=%d,", memory.readbyte(0x0210F014)))
	file:write("},\n")
end)

emu.registerexit(function()
	file:write("}\n")
	file:close()
end)
